module.exports = {
    cookieName: 'hzieeCookie',
    loginUrl: 'http://jxgl.hziee.edu.cn/default2.aspx',
    timeTableUrl: 'http://jxgl.hziee.edu.cn/xskbcx.aspx?xh=',
    mainUrl: 'http://jxgl.hziee.edu.cn/xs_main.aspx?xh=',
    examUrl: 'http://jxgl.hziee.edu.cn/xskscx.aspx?xh=',
    gradeUrl: 'http://jxgl.hziee.edu.cn/xscjcx_dq.aspx?xh=',
    teacherExamUrl: 'http://jxgl.hziee.edu.cn/js_ksap.aspx?zgh=',
    loginConfig: {
        __VIEWSTATE: '/wEPDwUKLTY4Mjg3NzI5NGRkHb6ppClKCzNjspPZo5RhJd2eBHA=',
        __EVENTVALIDATION: '/wEWCgLDqd+VAgLs0bLrBgLs0fbZDAK/wuqQDgKAqenNDQLN7c0VAuaMg+INAveMotMNAoznisYGArursYYIFhbjTihUHPPoe7ok9ErA9YWV8K0=',
        RadioButtonList1: '学生',
        Button1: '',
    },
    teacherLoginConfig: {
        __VIEWSTATE:'/wEPDwUKLTY4Mjg3NzI5NGRkHb6ppClKCzNjspPZo5RhJd2eBHA=',
        __EVENTVALIDATION:'/wEWCgLDqd+VAgLs0bLrBgLs0fbZDAK/wuqQDgKAqenNDQLN7c0VAuaMg+INAveMotMNAoznisYGArursYYIFhbjTihUHPPoe7ok9ErA9YWV8K0=',
        RadioButtonList1:'教师',
        Button1: ''
    },
    headerConfig: {
        'Host': 'jxgl.hziee.edu.cn',
        'Connection': 'keep-alive',
        'Cache-Control': 'max-age=0',
        'Origin': 'http://jxgl.hziee.edu.cn',
        'Upgrade-Insecure-Requests': 1,
        'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36',
        // 'Content-Type': 'application/x-www-form-urlencoded',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
        'Referer': 'http://jxgl.hziee.edu.cn/default2.aspx',
        'Accept-Encoding': 'gzip, deflate',
        'Accept-Language': 'zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4',
        // 'Content-Length': 285,
    },   
    dbConfig: {
        'host': '',
        'port': '3306',
        'database': '',
        'user': 'root',
        'password': 'pwd123456',
    },
    weeks: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    startTimes: ['00:00', '8:20', '9:10', '10:05', '10:55', '11:45', '13:30', '14:20', '15:10', '16:00', '18:15', '19:05', '19:55'],
    endTimes: ['00:00', '9:05', '9:55', '10:50', '11:40', '12:30', '14:15', '15:05', '15:55', '16:45', '19:00', '19:50', '20:40'],
};
